### ISSUE TITLE
Guzzle Http Version Incompatibility

### ISSUE THREAD

**Issue by AH-KHAN** [motveu/php-api-sdk#1]
In Laravel 8:
  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - motveu/php-api-sdk v0.4 requires guzzlehttp/guzzle ^6.4 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for motveu/php-api-sdk ^0.4.0 -> satisfiable by motveu/php-api-sdk[v0.4].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    
While we can not downgrade guzzlehttp due to laravel requirements.

I forked in tested in the newer version of guzzlehttp 7.0.1, it is working fine. Would you please change the version?

**Comment by jakubvojacek** [comment]
yes, I'll update the dependency shortly, thank you

**Comment by jakubvojacek** [comment]
Addressed in https://github.com/motveu/php-api-sdk/commit/9238c1d5720b48a60ed894eae3a7422469b3d2f2

please test

**Comment by AH-KHAN** [comment]
Thank you very much, The issue is resolved!.
